"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProvider from "../app/components/ClientProvider";
import { AuthProvider } from "../app/context/AuthContext";
import { CartProvider } from "../app/context/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Main Layout Component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Inline Metadata */}
        <title>LUXORA</title>
        <meta name="description" content="Generated by create next app"></meta>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Auth & Cart Context Wrappers */}
        <AuthProvider>
          <CartProvider>
            <ClientProvider>{children}</ClientProvider>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
