// No "use client" since this is primarily a server component for global metadata and structure.
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProvider from "../app/components/ClientProvider";
import { AuthProvider } from "../app/context/AuthContext"; // Ensure correct import path
import { CartProvider } from "../app/context/CartContext";

// Google Fonts Declaration
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata for the page
export const metadata = {
  title: "LUXORA",
  description: "Generated by create next app",
};

// Main Layout Component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {" "}
      {/* Required HTML tag */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Auth & Cart Context Wrappers */}
        <AuthProvider>
          <CartProvider>
            {/* Ensure ClientProvider handles client-specific logic */}
            <ClientProvider>{children}</ClientProvider>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
